version: '3'
services:
  postgres-service:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=outgive
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-app-service:
    build:
      context: ./web-app-service
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web-app-service:/app
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - api-service

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./api-service:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres-service
      - PGDATABASE=outgive
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on: 
      postgres-service:
        condition: service_healthy

